FROM python:3.9-slim
RUN pip install poetry
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --no-dev
# Copy in everything else:
COPY . .
RUN poetry install --no-dev

RUN python main.py
