---

version: 1
formatters:
  simple:
    format: '%(asctime)s:%(levelname)-5s %(message)s'
    datefmt: '%Y-%m-%d_%H:%M:%S'
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s:%(levelname)-8s:%(name)-15s:%(message)s'
    datefmt: '%Y-%m-%d_%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: brief
    stream: ext://sys.stdout
  generate:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logs/generate.log
    maxBytes: 16384
    backupCount: 3
loggers:
  __main__:
    level: DEBUG
    handlers: [console,generate]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
