name: Python Coverage Workflow
on:
  # Trigger analysis when pushing in main or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - garymcwilliams/issue43-github-actions # only kep for future reference
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  sonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
#      with:
#        projectBaseDir: ical
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}