name: GitHub CI
on:
  push:
#on:
#  push:
#    branches:
#      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.13]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup
      uses: actions/checkout@v3
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      uses: snok/install-poetry@v1
      with:
        version: ${{ matrix.poetry-version }}
    - name: poetry in motion
      run: |
        poetry run pytest tests --cov=./ --cov-report=xml

# Use a separate flow, as we only want to upload one set of codecov results
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        poetry-version: 1.1.13
    - name: Generate coverage report
      run: |
        poetry run pytest tests --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
